name: Crossbow nightly report R tests

on:
  pull_request:
    paths:
      - 'crossbow-nightly-report/**'
      - ".github/workflows/crossbow-nightly-report-r-tests.yml"
  push:
    branches: main
    paths:
      - 'crossbow-nightly-report/**'
      - ".github/workflows/crossbow-nightly-report-r-tests.yml"


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crossbow-nightly-report

    steps:
    - uses: actions/checkout@v3


    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'renv'
        use-public-rspm: true
        working-directory: ./crossbow-nightly-report

    - name: Restore packages using renv
      uses: r-lib/actions/setup-renv@v2
      with: 
        working-directory: ./crossbow-nightly-report
        cache-version: 3

    - name: Install test dependencies
      run: install.packages('testthat')
      shell: Rscript {0}

    - name: Run tests
      run: |
        library(testthat)
        test_results <- test_dir("tests", reporter = "summary", stop_on_failure = FALSE)
        test_result_df <- as.data.frame(test_results)
        # Exit with error code if any tests failed
        if (length(test_results) > 0 && any(c(test_result_df$failed, test_result_df$error))) {
          quit(status = 1)
        }
      shell: Rscript {0}