name: Report tests

on:
  push:
    paths:
      - '.github/workflows/nightly_tests_report.yml'
  schedule:
    - cron: '0 11 * * *'

jobs:
  nightly_tests_report:
    uses: ursacomputing/crossbow/.github/workflows/report.yml@master
    with:
      report_type: tests
